name: Running Checks on Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    run-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v1
        with:
          go-version: 1.23
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run Unit test
        run: make test